# Generated by Django 5.2.17 on 2026-09-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('WEAPON', 'Weapon'), ('AMMUNITION', 'Ammunition'), ('COMMUNICATION', 'Communication Equipment'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
