# Generated by Django 5.2.17 on 2026-09-30 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bases', '0001_initial'),
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('expenditure_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenditures', to='bases.base')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenditures', to='equipment.equipmenttype')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenditures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
